window.WC2026_DATA = {
  "summary": {
    "totalJogos": 104,
    "faseGrupos": 72,
    "mataMata": 32,
    "grupos": 12,
    "selecoes": 48,
    "periodo": "2026-06-11 a 2026-07-19",
    "resultadosReais": 74,
    "simulados": 30
  },
  "groups": [
    {
      "grupo": "A",
      "equipes": [
        "México",
        "África do Sul",
        "Coreia do Sul",
        "Tchéquia"
      ]
    },
    {
      "grupo": "B",
      "equipes": [
        "Canadá",
        "Bósnia e Herzegovina",
        "Catar",
        "Suíça"
      ]
    },
    {
      "grupo": "C",
      "equipes": [
        "Haiti",
        "Escócia",
        "Brasil",
        "Marrocos"
      ]
    },
    {
      "grupo": "D",
      "equipes": [
        "Estados Unidos",
        "Paraguai",
        "Austrália",
        "Turquia"
      ]
    },
    {
      "grupo": "E",
      "equipes": [
        "Costa do Marfim",
        "Equador",
        "Alemanha",
        "Curaçao"
      ]
    },
    {
      "grupo": "F",
      "equipes": [
        "Países Baixos",
        "Japão",
        "Suécia",
        "Tunísia"
      ]
    },
    {
      "grupo": "G",
      "equipes": [
        "Irã",
        "Nova Zelândia",
        "Bélgica",
        "Egito"
      ]
    },
    {
      "grupo": "H",
      "equipes": [
        "Arábia Saudita",
        "Uruguai",
        "Espanha",
        "Cabo Verde"
      ]
    },
    {
      "grupo": "I",
      "equipes": [
        "França",
        "Senegal",
        "Iraque",
        "Noruega"
      ]
    },
    {
      "grupo": "J",
      "equipes": [
        "Argentina",
        "Argélia",
        "Áustria",
        "Jordânia"
      ]
    },
    {
      "grupo": "K",
      "equipes": [
        "Portugal",
        "RD Congo",
        "Uzbequistão",
        "Colômbia"
      ]
    },
    {
      "grupo": "L",
      "equipes": [
        "Gana",
        "Panamá",
        "Inglaterra",
        "Croácia"
      ]
    }
  ],
  "matches": [
    {
      "jogo": 1,
      "data": "2026-06-11",
      "diaSemana": "Quinta-feira",
      "horaET": "15:00",
      "horaLocal": "13:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "A",
      "rodadaGrupo": 1.0,
      "equipe1": "México",
      "equipe2": "África do Sul",
      "confronto": "México x África do Sul",
      "estadio": "Estadio Azteca",
      "cidade": "Mexico City",
      "pais": "México",
      "status": "Finalizado",
      "data_dt": "2026-06-11",
      "placar_real": "2-0",
      "vencedor_real": "México",
      "gols1_real": 2.0,
      "gols2_real": 0.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "México 2 x 0 África do Sul"
    },
    {
      "jogo": 2,
      "data": "2026-06-11",
      "diaSemana": "Quinta-feira",
      "horaET": "22:00",
      "horaLocal": "20:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "A",
      "rodadaGrupo": 1.0,
      "equipe1": "Coreia do Sul",
      "equipe2": "Tchéquia",
      "confronto": "Coreia do Sul x Tchéquia",
      "estadio": "Estadio Akron",
      "cidade": "Guadalajara",
      "pais": "México",
      "status": "Finalizado",
      "data_dt": "2026-06-11",
      "placar_real": "2-1",
      "vencedor_real": "Coreia do Sul",
      "gols1_real": 2.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "República da Coreia 2 x 1 Tchéquia"
    },
    {
      "jogo": 3,
      "data": "2026-06-12",
      "diaSemana": "Sexta-feira",
      "horaET": "15:00",
      "horaLocal": "15:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "B",
      "rodadaGrupo": 1.0,
      "equipe1": "Canadá",
      "equipe2": "Bósnia e Herzegovina",
      "confronto": "Canadá x Bósnia e Herzegovina",
      "estadio": "BMO Field",
      "cidade": "Toronto",
      "pais": "Canadá",
      "status": "Finalizado",
      "data_dt": "2026-06-12",
      "placar_real": "1-1",
      "vencedor_real": "Empate",
      "gols1_real": 1.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Canadá 1 x 1 Bósnia e Herzegovina"
    },
    {
      "jogo": 4,
      "data": "2026-06-12",
      "diaSemana": "Sexta-feira",
      "horaET": "21:00",
      "horaLocal": "18:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "D",
      "rodadaGrupo": 1.0,
      "equipe1": "Estados Unidos",
      "equipe2": "Paraguai",
      "confronto": "Estados Unidos x Paraguai",
      "estadio": "SoFi Stadium",
      "cidade": "Los Angeles",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-12",
      "placar_real": "4-1",
      "vencedor_real": "Estados Unidos",
      "gols1_real": 4.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Estados Unidos 4 x 1 Paraguai"
    },
    {
      "jogo": 5,
      "data": "2026-06-13",
      "diaSemana": "Sábado",
      "horaET": "21:00",
      "horaLocal": "21:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "C",
      "rodadaGrupo": 1.0,
      "equipe1": "Haiti",
      "equipe2": "Escócia",
      "confronto": "Haiti x Escócia",
      "estadio": "Gillette Stadium",
      "cidade": "Boston",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-13",
      "placar_real": "0-1",
      "vencedor_real": "Escócia",
      "gols1_real": 0.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Haiti 0 x 1 Escócia"
    },
    {
      "jogo": 6,
      "data": "2026-06-13",
      "diaSemana": "Sábado",
      "horaET": "24:00",
      "horaLocal": "21:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "D",
      "rodadaGrupo": 1.0,
      "equipe1": "Austrália",
      "equipe2": "Turquia",
      "confronto": "Austrália x Turquia",
      "estadio": "BC Place",
      "cidade": "Vancouver",
      "pais": "Canadá",
      "status": "Finalizado",
      "data_dt": "2026-06-13",
      "placar_real": "2-0",
      "vencedor_real": "Austrália",
      "gols1_real": 2.0,
      "gols2_real": 0.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Austrália 2 x 0 Turquia"
    },
    {
      "jogo": 7,
      "data": "2026-06-13",
      "diaSemana": "Sábado",
      "horaET": "18:00",
      "horaLocal": "18:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "C",
      "rodadaGrupo": 1.0,
      "equipe1": "Brasil",
      "equipe2": "Marrocos",
      "confronto": "Brasil x Marrocos",
      "estadio": "MetLife Stadium",
      "cidade": "New York/New Jersey",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-13",
      "placar_real": "1-1",
      "vencedor_real": "Empate",
      "gols1_real": 1.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Brasil 1 x 1 Marrocos"
    },
    {
      "jogo": 8,
      "data": "2026-06-13",
      "diaSemana": "Sábado",
      "horaET": "15:00",
      "horaLocal": "12:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "B",
      "rodadaGrupo": 1.0,
      "equipe1": "Catar",
      "equipe2": "Suíça",
      "confronto": "Catar x Suíça",
      "estadio": "Levi's Stadium",
      "cidade": "San Francisco Bay Area",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-13",
      "placar_real": "1-1",
      "vencedor_real": "Empate",
      "gols1_real": 1.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Catar 1 x 1 Suíça"
    },
    {
      "jogo": 9,
      "data": "2026-06-14",
      "diaSemana": "Domingo",
      "horaET": "19:00",
      "horaLocal": "19:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "E",
      "rodadaGrupo": 1.0,
      "equipe1": "Costa do Marfim",
      "equipe2": "Equador",
      "confronto": "Costa do Marfim x Equador",
      "estadio": "Lincoln Financial Field",
      "cidade": "Philadelphia",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-14",
      "placar_real": "1-0",
      "vencedor_real": "Costa do Marfim",
      "gols1_real": 1.0,
      "gols2_real": 0.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Costa do Marfim 1 x 0 Equador"
    },
    {
      "jogo": 10,
      "data": "2026-06-14",
      "diaSemana": "Domingo",
      "horaET": "13:00",
      "horaLocal": "12:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "E",
      "rodadaGrupo": 1.0,
      "equipe1": "Alemanha",
      "equipe2": "Curaçao",
      "confronto": "Alemanha x Curaçao",
      "estadio": "NRG Stadium",
      "cidade": "Houston",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-14",
      "placar_real": "7-1",
      "vencedor_real": "Alemanha",
      "gols1_real": 7.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Alemanha 7 x 1 Curaçao"
    },
    {
      "jogo": 11,
      "data": "2026-06-14",
      "diaSemana": "Domingo",
      "horaET": "16:00",
      "horaLocal": "15:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "F",
      "rodadaGrupo": 1.0,
      "equipe1": "Países Baixos",
      "equipe2": "Japão",
      "confronto": "Países Baixos x Japão",
      "estadio": "AT&T Stadium",
      "cidade": "Dallas",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-14",
      "placar_real": "2-2",
      "vencedor_real": "Empate",
      "gols1_real": 2.0,
      "gols2_real": 2.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Holanda 2 x 2 Japão"
    },
    {
      "jogo": 12,
      "data": "2026-06-14",
      "diaSemana": "Domingo",
      "horaET": "22:00",
      "horaLocal": "20:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "F",
      "rodadaGrupo": 1.0,
      "equipe1": "Suécia",
      "equipe2": "Tunísia",
      "confronto": "Suécia x Tunísia",
      "estadio": "Estadio BBVA",
      "cidade": "Monterrey",
      "pais": "México",
      "status": "Finalizado",
      "data_dt": "2026-06-14",
      "placar_real": "5-1",
      "vencedor_real": "Suécia",
      "gols1_real": 5.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Suécia 5 x 1 Tunísia"
    },
    {
      "jogo": 13,
      "data": "2026-06-15",
      "diaSemana": "Segunda-feira",
      "horaET": "18:00",
      "horaLocal": "18:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "H",
      "rodadaGrupo": 1.0,
      "equipe1": "Arábia Saudita",
      "equipe2": "Uruguai",
      "confronto": "Arábia Saudita x Uruguai",
      "estadio": "Hard Rock Stadium",
      "cidade": "Miami",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-15",
      "placar_real": "1-1",
      "vencedor_real": "Empate",
      "gols1_real": 1.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Arábia Saudita 1 x 1 Uruguai"
    },
    {
      "jogo": 14,
      "data": "2026-06-15",
      "diaSemana": "Segunda-feira",
      "horaET": "12:00",
      "horaLocal": "12:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "H",
      "rodadaGrupo": 1.0,
      "equipe1": "Espanha",
      "equipe2": "Cabo Verde",
      "confronto": "Espanha x Cabo Verde",
      "estadio": "Mercedes-Benz Stadium",
      "cidade": "Atlanta",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-15",
      "placar_real": "0-0",
      "vencedor_real": "Empate",
      "gols1_real": 0.0,
      "gols2_real": 0.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Espanha 0 x 0 Cabo Verde"
    },
    {
      "jogo": 15,
      "data": "2026-06-15",
      "diaSemana": "Segunda-feira",
      "horaET": "21:00",
      "horaLocal": "18:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "G",
      "rodadaGrupo": 1.0,
      "equipe1": "Irã",
      "equipe2": "Nova Zelândia",
      "confronto": "Irã x Nova Zelândia",
      "estadio": "SoFi Stadium",
      "cidade": "Los Angeles",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-15",
      "placar_real": "2-2",
      "vencedor_real": "Empate",
      "gols1_real": 2.0,
      "gols2_real": 2.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Irã 2 x 2 Nova Zelândia"
    },
    {
      "jogo": 16,
      "data": "2026-06-15",
      "diaSemana": "Segunda-feira",
      "horaET": "15:00",
      "horaLocal": "12:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "G",
      "rodadaGrupo": 1.0,
      "equipe1": "Bélgica",
      "equipe2": "Egito",
      "confronto": "Bélgica x Egito",
      "estadio": "Lumen Field",
      "cidade": "Seattle",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-15",
      "placar_real": "1-1",
      "vencedor_real": "Empate",
      "gols1_real": 1.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Bélgica 1 x 1 Egito"
    },
    {
      "jogo": 17,
      "data": "2026-06-16",
      "diaSemana": "Terça-feira",
      "horaET": "15:00",
      "horaLocal": "15:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "I",
      "rodadaGrupo": 1.0,
      "equipe1": "França",
      "equipe2": "Senegal",
      "confronto": "França x Senegal",
      "estadio": "MetLife Stadium",
      "cidade": "New York/New Jersey",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-16",
      "placar_real": "3-1",
      "vencedor_real": "França",
      "gols1_real": 3.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "França 3 x 1 Senegal"
    },
    {
      "jogo": 18,
      "data": "2026-06-16",
      "diaSemana": "Terça-feira",
      "horaET": "18:00",
      "horaLocal": "18:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "I",
      "rodadaGrupo": 1.0,
      "equipe1": "Iraque",
      "equipe2": "Noruega",
      "confronto": "Iraque x Noruega",
      "estadio": "Gillette Stadium",
      "cidade": "Boston",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-16",
      "placar_real": "1-4",
      "vencedor_real": "Noruega",
      "gols1_real": 1.0,
      "gols2_real": 4.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Iraque 1 x 4 Noruega"
    },
    {
      "jogo": 19,
      "data": "2026-06-16",
      "diaSemana": "Terça-feira",
      "horaET": "21:00",
      "horaLocal": "20:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "J",
      "rodadaGrupo": 1.0,
      "equipe1": "Argentina",
      "equipe2": "Argélia",
      "confronto": "Argentina x Argélia",
      "estadio": "Arrowhead Stadium",
      "cidade": "Kansas City",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-16",
      "placar_real": "3-0",
      "vencedor_real": "Argentina",
      "gols1_real": 3.0,
      "gols2_real": 0.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Argentina 3 x 0 Argélia"
    },
    {
      "jogo": 20,
      "data": "2026-06-16",
      "diaSemana": "Terça-feira",
      "horaET": "24:00",
      "horaLocal": "21:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "J",
      "rodadaGrupo": 1.0,
      "equipe1": "Áustria",
      "equipe2": "Jordânia",
      "confronto": "Áustria x Jordânia",
      "estadio": "Levi's Stadium",
      "cidade": "San Francisco Bay Area",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-16",
      "placar_real": "3-1",
      "vencedor_real": "Áustria",
      "gols1_real": 3.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Áustria 3 x 1 Jordânia"
    },
    {
      "jogo": 21,
      "data": "2026-06-17",
      "diaSemana": "Quarta-feira",
      "horaET": "19:00",
      "horaLocal": "19:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "L",
      "rodadaGrupo": 1.0,
      "equipe1": "Gana",
      "equipe2": "Panamá",
      "confronto": "Gana x Panamá",
      "estadio": "BMO Field",
      "cidade": "Toronto",
      "pais": "Canadá",
      "status": "Finalizado",
      "data_dt": "2026-06-17",
      "placar_real": "1-0",
      "vencedor_real": "Gana",
      "gols1_real": 1.0,
      "gols2_real": 0.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Gana 1 x 0 Panamá"
    },
    {
      "jogo": 22,
      "data": "2026-06-17",
      "diaSemana": "Quarta-feira",
      "horaET": "16:00",
      "horaLocal": "15:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "L",
      "rodadaGrupo": 1.0,
      "equipe1": "Inglaterra",
      "equipe2": "Croácia",
      "confronto": "Inglaterra x Croácia",
      "estadio": "AT&T Stadium",
      "cidade": "Dallas",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-17",
      "placar_real": "4-2",
      "vencedor_real": "Inglaterra",
      "gols1_real": 4.0,
      "gols2_real": 2.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Inglaterra 4 x 2 Croácia"
    },
    {
      "jogo": 23,
      "data": "2026-06-17",
      "diaSemana": "Quarta-feira",
      "horaET": "13:00",
      "horaLocal": "12:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "K",
      "rodadaGrupo": 1.0,
      "equipe1": "Portugal",
      "equipe2": "RD Congo",
      "confronto": "Portugal x RD Congo",
      "estadio": "NRG Stadium",
      "cidade": "Houston",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-17",
      "placar_real": "1-1",
      "vencedor_real": "Empate",
      "gols1_real": 1.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Portugal 1 x 1 RD do Congo"
    },
    {
      "jogo": 24,
      "data": "2026-06-17",
      "diaSemana": "Quarta-feira",
      "horaET": "22:00",
      "horaLocal": "20:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "K",
      "rodadaGrupo": 1.0,
      "equipe1": "Uzbequistão",
      "equipe2": "Colômbia",
      "confronto": "Uzbequistão x Colômbia",
      "estadio": "Estadio Azteca",
      "cidade": "Mexico City",
      "pais": "México",
      "status": "Finalizado",
      "data_dt": "2026-06-17",
      "placar_real": "1-3",
      "vencedor_real": "Colômbia",
      "gols1_real": 1.0,
      "gols2_real": 3.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Uzbequistão 1 x 3 Colômbia"
    },
    {
      "jogo": 25,
      "data": "2026-06-18",
      "diaSemana": "Quinta-feira",
      "horaET": "12:00",
      "horaLocal": "12:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "A",
      "rodadaGrupo": 2.0,
      "equipe1": "Tchéquia",
      "equipe2": "África do Sul",
      "confronto": "Tchéquia x África do Sul",
      "estadio": "Mercedes-Benz Stadium",
      "cidade": "Atlanta",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-18",
      "placar_real": "1-1",
      "vencedor_real": "Empate",
      "gols1_real": 1.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Tchéquia 1 x 1 África do Sul"
    },
    {
      "jogo": 26,
      "data": "2026-06-18",
      "diaSemana": "Quinta-feira",
      "horaET": "15:00",
      "horaLocal": "12:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "B",
      "rodadaGrupo": 2.0,
      "equipe1": "Suíça",
      "equipe2": "Bósnia e Herzegovina",
      "confronto": "Suíça x Bósnia e Herzegovina",
      "estadio": "SoFi Stadium",
      "cidade": "Los Angeles",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-18",
      "placar_real": "4-1",
      "vencedor_real": "Suíça",
      "gols1_real": 4.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Suíça 4 x 1 Bósnia e Herzegovina"
    },
    {
      "jogo": 27,
      "data": "2026-06-18",
      "diaSemana": "Quinta-feira",
      "horaET": "18:00",
      "horaLocal": "15:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "B",
      "rodadaGrupo": 2.0,
      "equipe1": "Canadá",
      "equipe2": "Catar",
      "confronto": "Canadá x Catar",
      "estadio": "BC Place",
      "cidade": "Vancouver",
      "pais": "Canadá",
      "status": "Finalizado",
      "data_dt": "2026-06-18",
      "placar_real": "6-0",
      "vencedor_real": "Canadá",
      "gols1_real": 6.0,
      "gols2_real": 0.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Canadá 6 x 0 Catar"
    },
    {
      "jogo": 28,
      "data": "2026-06-18",
      "diaSemana": "Quinta-feira",
      "horaET": "21:00",
      "horaLocal": "19:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "A",
      "rodadaGrupo": 2.0,
      "equipe1": "México",
      "equipe2": "Coreia do Sul",
      "confronto": "México x Coreia do Sul",
      "estadio": "Estadio Akron",
      "cidade": "Guadalajara",
      "pais": "México",
      "status": "Finalizado",
      "data_dt": "2026-06-18",
      "placar_real": "1-0",
      "vencedor_real": "México",
      "gols1_real": 1.0,
      "gols2_real": 0.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "México 1 x 0 República da Coreia"
    },
    {
      "jogo": 29,
      "data": "2026-06-19",
      "diaSemana": "Sexta-feira",
      "horaET": "21:00",
      "horaLocal": "21:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "C",
      "rodadaGrupo": 2.0,
      "equipe1": "Brasil",
      "equipe2": "Haiti",
      "confronto": "Brasil x Haiti",
      "estadio": "Lincoln Financial Field",
      "cidade": "Philadelphia",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-19",
      "placar_real": "3-0",
      "vencedor_real": "Brasil",
      "gols1_real": 3.0,
      "gols2_real": 0.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Brasil 3 x 0 Haiti"
    },
    {
      "jogo": 30,
      "data": "2026-06-19",
      "diaSemana": "Sexta-feira",
      "horaET": "18:00",
      "horaLocal": "18:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "C",
      "rodadaGrupo": 2.0,
      "equipe1": "Escócia",
      "equipe2": "Marrocos",
      "confronto": "Escócia x Marrocos",
      "estadio": "Gillette Stadium",
      "cidade": "Boston",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-19",
      "placar_real": "0-1",
      "vencedor_real": "Marrocos",
      "gols1_real": 0.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Escócia 0 x 1 Marrocos"
    },
    {
      "jogo": 31,
      "data": "2026-06-19",
      "diaSemana": "Sexta-feira",
      "horaET": "23:00",
      "horaLocal": "20:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "D",
      "rodadaGrupo": 2.0,
      "equipe1": "Turquia",
      "equipe2": "Paraguai",
      "confronto": "Turquia x Paraguai",
      "estadio": "Levi's Stadium",
      "cidade": "San Francisco Bay Area",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-19",
      "placar_real": "0-1",
      "vencedor_real": "Paraguai",
      "gols1_real": 0.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Turquia 0 x 1 Paraguai"
    },
    {
      "jogo": 32,
      "data": "2026-06-19",
      "diaSemana": "Sexta-feira",
      "horaET": "15:00",
      "horaLocal": "12:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "D",
      "rodadaGrupo": 2.0,
      "equipe1": "Estados Unidos",
      "equipe2": "Austrália",
      "confronto": "Estados Unidos x Austrália",
      "estadio": "Lumen Field",
      "cidade": "Seattle",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-19",
      "placar_real": "2-0",
      "vencedor_real": "Estados Unidos",
      "gols1_real": 2.0,
      "gols2_real": 0.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Estados Unidos 2 x 0 Austrália"
    },
    {
      "jogo": 33,
      "data": "2026-06-20",
      "diaSemana": "Sábado",
      "horaET": "16:00",
      "horaLocal": "16:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "E",
      "rodadaGrupo": 2.0,
      "equipe1": "Alemanha",
      "equipe2": "Costa do Marfim",
      "confronto": "Alemanha x Costa do Marfim",
      "estadio": "BMO Field",
      "cidade": "Toronto",
      "pais": "Canadá",
      "status": "Finalizado",
      "data_dt": "2026-06-20",
      "placar_real": "2-1",
      "vencedor_real": "Alemanha",
      "gols1_real": 2.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Alemanha 2 x 1 Costa do Marfim"
    },
    {
      "jogo": 34,
      "data": "2026-06-20",
      "diaSemana": "Sábado",
      "horaET": "20:00",
      "horaLocal": "19:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "E",
      "rodadaGrupo": 2.0,
      "equipe1": "Equador",
      "equipe2": "Curaçao",
      "confronto": "Equador x Curaçao",
      "estadio": "Arrowhead Stadium",
      "cidade": "Kansas City",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-20",
      "placar_real": "0-0",
      "vencedor_real": "Empate",
      "gols1_real": 0.0,
      "gols2_real": 0.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Equador 0 x 0 Curaçao"
    },
    {
      "jogo": 35,
      "data": "2026-06-20",
      "diaSemana": "Sábado",
      "horaET": "13:00",
      "horaLocal": "12:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "F",
      "rodadaGrupo": 2.0,
      "equipe1": "Países Baixos",
      "equipe2": "Suécia",
      "confronto": "Países Baixos x Suécia",
      "estadio": "NRG Stadium",
      "cidade": "Houston",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-20",
      "placar_real": "5-1",
      "vencedor_real": "Países Baixos",
      "gols1_real": 5.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Holanda 5 x 1 Suécia"
    },
    {
      "jogo": 36,
      "data": "2026-06-20",
      "diaSemana": "Sábado",
      "horaET": "24:00",
      "horaLocal": "22:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "F",
      "rodadaGrupo": 2.0,
      "equipe1": "Tunísia",
      "equipe2": "Japão",
      "confronto": "Tunísia x Japão",
      "estadio": "Estadio BBVA",
      "cidade": "Monterrey",
      "pais": "México",
      "status": "Finalizado",
      "data_dt": "2026-06-20",
      "placar_real": "0-4",
      "vencedor_real": "Japão",
      "gols1_real": 0.0,
      "gols2_real": 4.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Tunísia 0 x 4 Japão"
    },
    {
      "jogo": 37,
      "data": "2026-06-21",
      "diaSemana": "Domingo",
      "horaET": "18:00",
      "horaLocal": "18:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "H",
      "rodadaGrupo": 2.0,
      "equipe1": "Uruguai",
      "equipe2": "Cabo Verde",
      "confronto": "Uruguai x Cabo Verde",
      "estadio": "Hard Rock Stadium",
      "cidade": "Miami",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-21",
      "placar_real": "2-2",
      "vencedor_real": "Empate",
      "gols1_real": 2.0,
      "gols2_real": 2.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Uruguai 2 x 2 Cabo Verde"
    },
    {
      "jogo": 38,
      "data": "2026-06-21",
      "diaSemana": "Domingo",
      "horaET": "12:00",
      "horaLocal": "12:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "H",
      "rodadaGrupo": 2.0,
      "equipe1": "Espanha",
      "equipe2": "Arábia Saudita",
      "confronto": "Espanha x Arábia Saudita",
      "estadio": "Mercedes-Benz Stadium",
      "cidade": "Atlanta",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-21",
      "placar_real": "4-0",
      "vencedor_real": "Espanha",
      "gols1_real": 4.0,
      "gols2_real": 0.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Espanha 4 x 0 Arábia Saudita"
    },
    {
      "jogo": 39,
      "data": "2026-06-21",
      "diaSemana": "Domingo",
      "horaET": "15:00",
      "horaLocal": "12:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "G",
      "rodadaGrupo": 2.0,
      "equipe1": "Bélgica",
      "equipe2": "Irã",
      "confronto": "Bélgica x Irã",
      "estadio": "SoFi Stadium",
      "cidade": "Los Angeles",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-21",
      "placar_real": "0-0",
      "vencedor_real": "Empate",
      "gols1_real": 0.0,
      "gols2_real": 0.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Bélgica 0 x 0 Irã"
    },
    {
      "jogo": 40,
      "data": "2026-06-21",
      "diaSemana": "Domingo",
      "horaET": "21:00",
      "horaLocal": "18:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "G",
      "rodadaGrupo": 2.0,
      "equipe1": "Nova Zelândia",
      "equipe2": "Egito",
      "confronto": "Nova Zelândia x Egito",
      "estadio": "BC Place",
      "cidade": "Vancouver",
      "pais": "Canadá",
      "status": "Finalizado",
      "data_dt": "2026-06-21",
      "placar_real": "1-3",
      "vencedor_real": "Egito",
      "gols1_real": 1.0,
      "gols2_real": 3.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Nova Zelândia 1 x 3 Egito"
    },
    {
      "jogo": 41,
      "data": "2026-06-22",
      "diaSemana": "Segunda-feira",
      "horaET": "20:00",
      "horaLocal": "20:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "I",
      "rodadaGrupo": 2.0,
      "equipe1": "Noruega",
      "equipe2": "Senegal",
      "confronto": "Noruega x Senegal",
      "estadio": "MetLife Stadium",
      "cidade": "New York/New Jersey",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-22",
      "placar_real": "3-2",
      "vencedor_real": "Noruega",
      "gols1_real": 3.0,
      "gols2_real": 2.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Noruega 3 x 2 Senegal"
    },
    {
      "jogo": 42,
      "data": "2026-06-22",
      "diaSemana": "Segunda-feira",
      "horaET": "17:00",
      "horaLocal": "17:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "I",
      "rodadaGrupo": 2.0,
      "equipe1": "França",
      "equipe2": "Iraque",
      "confronto": "França x Iraque",
      "estadio": "Lincoln Financial Field",
      "cidade": "Philadelphia",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-22",
      "placar_real": "3-0",
      "vencedor_real": "França",
      "gols1_real": 3.0,
      "gols2_real": 0.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "França 3 x 0 Iraque"
    },
    {
      "jogo": 43,
      "data": "2026-06-22",
      "diaSemana": "Segunda-feira",
      "horaET": "13:00",
      "horaLocal": "12:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "J",
      "rodadaGrupo": 2.0,
      "equipe1": "Argentina",
      "equipe2": "Áustria",
      "confronto": "Argentina x Áustria",
      "estadio": "AT&T Stadium",
      "cidade": "Dallas",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-22",
      "placar_real": "2-0",
      "vencedor_real": "Argentina",
      "gols1_real": 2.0,
      "gols2_real": 0.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Argentina 2 x 0 Áustria"
    },
    {
      "jogo": 44,
      "data": "2026-06-22",
      "diaSemana": "Segunda-feira",
      "horaET": "23:00",
      "horaLocal": "20:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "J",
      "rodadaGrupo": 2.0,
      "equipe1": "Jordânia",
      "equipe2": "Argélia",
      "confronto": "Jordânia x Argélia",
      "estadio": "Levi's Stadium",
      "cidade": "San Francisco Bay Area",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-22",
      "placar_real": "1-2",
      "vencedor_real": "Argélia",
      "gols1_real": 1.0,
      "gols2_real": 2.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Jordânia 1 x 2 Argélia"
    },
    {
      "jogo": 45,
      "data": "2026-06-23",
      "diaSemana": "Terça-feira",
      "horaET": "16:00",
      "horaLocal": "16:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "L",
      "rodadaGrupo": 2.0,
      "equipe1": "Inglaterra",
      "equipe2": "Gana",
      "confronto": "Inglaterra x Gana",
      "estadio": "Gillette Stadium",
      "cidade": "Boston",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-23",
      "placar_real": "0-0",
      "vencedor_real": "Empate",
      "gols1_real": 0.0,
      "gols2_real": 0.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Inglaterra 0 x 0 Gana"
    },
    {
      "jogo": 46,
      "data": "2026-06-23",
      "diaSemana": "Terça-feira",
      "horaET": "19:00",
      "horaLocal": "19:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "L",
      "rodadaGrupo": 2.0,
      "equipe1": "Panamá",
      "equipe2": "Croácia",
      "confronto": "Panamá x Croácia",
      "estadio": "BMO Field",
      "cidade": "Toronto",
      "pais": "Canadá",
      "status": "Finalizado",
      "data_dt": "2026-06-23",
      "placar_real": "0-1",
      "vencedor_real": "Croácia",
      "gols1_real": 0.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Panamá 0 x 1 Croácia"
    },
    {
      "jogo": 47,
      "data": "2026-06-23",
      "diaSemana": "Terça-feira",
      "horaET": "13:00",
      "horaLocal": "12:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "K",
      "rodadaGrupo": 2.0,
      "equipe1": "Portugal",
      "equipe2": "Uzbequistão",
      "confronto": "Portugal x Uzbequistão",
      "estadio": "NRG Stadium",
      "cidade": "Houston",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-23",
      "placar_real": "5-0",
      "vencedor_real": "Portugal",
      "gols1_real": 5.0,
      "gols2_real": 0.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Portugal 5 x 0 Uzbequistão"
    },
    {
      "jogo": 48,
      "data": "2026-06-23",
      "diaSemana": "Terça-feira",
      "horaET": "22:00",
      "horaLocal": "20:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "K",
      "rodadaGrupo": 2.0,
      "equipe1": "Colômbia",
      "equipe2": "RD Congo",
      "confronto": "Colômbia x RD Congo",
      "estadio": "Estadio Akron",
      "cidade": "Guadalajara",
      "pais": "México",
      "status": "Finalizado",
      "data_dt": "2026-06-23",
      "placar_real": "1-0",
      "vencedor_real": "Colômbia",
      "gols1_real": 1.0,
      "gols2_real": 0.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Colômbia 1 x 0 RD do Congo"
    },
    {
      "jogo": 49,
      "data": "2026-06-24",
      "diaSemana": "Quarta-feira",
      "horaET": "18:00",
      "horaLocal": "18:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "C",
      "rodadaGrupo": 3.0,
      "equipe1": "Escócia",
      "equipe2": "Brasil",
      "confronto": "Escócia x Brasil",
      "estadio": "Hard Rock Stadium",
      "cidade": "Miami",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-24",
      "placar_real": "0-3",
      "vencedor_real": "Brasil",
      "gols1_real": 0.0,
      "gols2_real": 3.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Escócia 0 x 3 Brasil"
    },
    {
      "jogo": 50,
      "data": "2026-06-24",
      "diaSemana": "Quarta-feira",
      "horaET": "18:00",
      "horaLocal": "18:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "C",
      "rodadaGrupo": 3.0,
      "equipe1": "Marrocos",
      "equipe2": "Haiti",
      "confronto": "Marrocos x Haiti",
      "estadio": "Mercedes-Benz Stadium",
      "cidade": "Atlanta",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-24",
      "placar_real": "4-2",
      "vencedor_real": "Marrocos",
      "gols1_real": 4.0,
      "gols2_real": 2.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Marrocos 4 x 2 Haiti"
    },
    {
      "jogo": 51,
      "data": "2026-06-24",
      "diaSemana": "Quarta-feira",
      "horaET": "15:00",
      "horaLocal": "12:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "B",
      "rodadaGrupo": 3.0,
      "equipe1": "Suíça",
      "equipe2": "Canadá",
      "confronto": "Suíça x Canadá",
      "estadio": "BC Place",
      "cidade": "Vancouver",
      "pais": "Canadá",
      "status": "Finalizado",
      "data_dt": "2026-06-24",
      "placar_real": "2-1",
      "vencedor_real": "Suíça",
      "gols1_real": 2.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Suíça 2 x 1 Canadá"
    },
    {
      "jogo": 52,
      "data": "2026-06-24",
      "diaSemana": "Quarta-feira",
      "horaET": "15:00",
      "horaLocal": "12:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "B",
      "rodadaGrupo": 3.0,
      "equipe1": "Bósnia e Herzegovina",
      "equipe2": "Catar",
      "confronto": "Bósnia e Herzegovina x Catar",
      "estadio": "Lumen Field",
      "cidade": "Seattle",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-24",
      "placar_real": "3-1",
      "vencedor_real": "Bósnia e Herzegovina",
      "gols1_real": 3.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Bósnia e Herzegovina 3 x 1 Catar"
    },
    {
      "jogo": 53,
      "data": "2026-06-24",
      "diaSemana": "Quarta-feira",
      "horaET": "21:00",
      "horaLocal": "19:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "A",
      "rodadaGrupo": 3.0,
      "equipe1": "Tchéquia",
      "equipe2": "México",
      "confronto": "Tchéquia x México",
      "estadio": "Estadio Azteca",
      "cidade": "Mexico City",
      "pais": "México",
      "status": "Finalizado",
      "data_dt": "2026-06-24",
      "placar_real": "0-3",
      "vencedor_real": "México",
      "gols1_real": 0.0,
      "gols2_real": 3.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "República Tcheca 0 x 3 México"
    },
    {
      "jogo": 54,
      "data": "2026-06-24",
      "diaSemana": "Quarta-feira",
      "horaET": "21:00",
      "horaLocal": "19:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "A",
      "rodadaGrupo": 3.0,
      "equipe1": "África do Sul",
      "equipe2": "Coreia do Sul",
      "confronto": "África do Sul x Coreia do Sul",
      "estadio": "Estadio BBVA",
      "cidade": "Monterrey",
      "pais": "México",
      "status": "Finalizado",
      "data_dt": "2026-06-24",
      "placar_real": "1-0",
      "vencedor_real": "África do Sul",
      "gols1_real": 1.0,
      "gols2_real": 0.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "África do Sul 1 x 0 República da Coreia"
    },
    {
      "jogo": 55,
      "data": "2026-06-25",
      "diaSemana": "Quinta-feira",
      "horaET": "16:00",
      "horaLocal": "16:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "E",
      "rodadaGrupo": 3.0,
      "equipe1": "Curaçao",
      "equipe2": "Costa do Marfim",
      "confronto": "Curaçao x Costa do Marfim",
      "estadio": "Lincoln Financial Field",
      "cidade": "Philadelphia",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-25",
      "placar_real": "0-2",
      "vencedor_real": "Costa do Marfim",
      "gols1_real": 0.0,
      "gols2_real": 2.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Curaçao 0 x 2 Costa do Marfim"
    },
    {
      "jogo": 56,
      "data": "2026-06-25",
      "diaSemana": "Quinta-feira",
      "horaET": "16:00",
      "horaLocal": "16:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "E",
      "rodadaGrupo": 3.0,
      "equipe1": "Equador",
      "equipe2": "Alemanha",
      "confronto": "Equador x Alemanha",
      "estadio": "MetLife Stadium",
      "cidade": "New York/New Jersey",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-25",
      "placar_real": "2-1",
      "vencedor_real": "Equador",
      "gols1_real": 2.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Equador 2 x 1 Alemanha"
    },
    {
      "jogo": 57,
      "data": "2026-06-25",
      "diaSemana": "Quinta-feira",
      "horaET": "19:00",
      "horaLocal": "18:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "F",
      "rodadaGrupo": 3.0,
      "equipe1": "Japão",
      "equipe2": "Suécia",
      "confronto": "Japão x Suécia",
      "estadio": "AT&T Stadium",
      "cidade": "Dallas",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-25",
      "placar_real": "1-1",
      "vencedor_real": "Empate",
      "gols1_real": 1.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Japão 1 x 1 Suécia"
    },
    {
      "jogo": 58,
      "data": "2026-06-25",
      "diaSemana": "Quinta-feira",
      "horaET": "19:00",
      "horaLocal": "18:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "F",
      "rodadaGrupo": 3.0,
      "equipe1": "Tunísia",
      "equipe2": "Países Baixos",
      "confronto": "Tunísia x Países Baixos",
      "estadio": "Arrowhead Stadium",
      "cidade": "Kansas City",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-25",
      "placar_real": "1-3",
      "vencedor_real": "Países Baixos",
      "gols1_real": 1.0,
      "gols2_real": 3.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Tunísia 1 x 3 Holanda"
    },
    {
      "jogo": 59,
      "data": "2026-06-25",
      "diaSemana": "Quinta-feira",
      "horaET": "22:00",
      "horaLocal": "19:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "D",
      "rodadaGrupo": 3.0,
      "equipe1": "Turquia",
      "equipe2": "Estados Unidos",
      "confronto": "Turquia x Estados Unidos",
      "estadio": "SoFi Stadium",
      "cidade": "Los Angeles",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-25",
      "placar_real": "3-2",
      "vencedor_real": "Turquia",
      "gols1_real": 3.0,
      "gols2_real": 2.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Turquia 3 x 2 Estados Unidos"
    },
    {
      "jogo": 60,
      "data": "2026-06-25",
      "diaSemana": "Quinta-feira",
      "horaET": "22:00",
      "horaLocal": "19:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "D",
      "rodadaGrupo": 3.0,
      "equipe1": "Paraguai",
      "equipe2": "Austrália",
      "confronto": "Paraguai x Austrália",
      "estadio": "Levi's Stadium",
      "cidade": "San Francisco Bay Area",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-25",
      "placar_real": "0-0",
      "vencedor_real": "Empate",
      "gols1_real": 0.0,
      "gols2_real": 0.0,
      "status_real": "Finalizado",
      "fonte": "https://exame.com/esporte/copa-do-mundo-2026-veja-os-resultados-de-todos-jogos-ate-aqui-dia-a-dia/",
      "placar_original": "Paraguai 0 x 0 Austrália"
    },
    {
      "jogo": 61,
      "data": "2026-06-26",
      "diaSemana": "Sexta-feira",
      "horaET": "15:00",
      "horaLocal": "15:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "I",
      "rodadaGrupo": 3.0,
      "equipe1": "Noruega",
      "equipe2": "França",
      "confronto": "Noruega x França",
      "estadio": "Gillette Stadium",
      "cidade": "Boston",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-26",
      "placar_real": "1-4",
      "vencedor_real": "França",
      "gols1_real": 1.0,
      "gols2_real": 4.0,
      "status_real": "Finalizado",
      "fonte": "https://www.foxsports.com/soccer/fifa-world-cup-men-norway-vs-france-jun-26-2026-game-boxscore-647676 | https://www.reuters.com/sports/soccer/dembele-hat-trick-helps-france-beat-second-string-norway-4-1-top-group-2026-06-26/",
      "placar_original": "Noruega 1 x 4 França"
    },
    {
      "jogo": 62,
      "data": "2026-06-26",
      "diaSemana": "Sexta-feira",
      "horaET": "15:00",
      "horaLocal": "15:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "I",
      "rodadaGrupo": 3.0,
      "equipe1": "Senegal",
      "equipe2": "Iraque",
      "confronto": "Senegal x Iraque",
      "estadio": "BMO Field",
      "cidade": "Toronto",
      "pais": "Canadá",
      "status": "Finalizado",
      "data_dt": "2026-06-26",
      "placar_real": "5-0",
      "vencedor_real": "Senegal",
      "gols1_real": 5.0,
      "gols2_real": 0.0,
      "status_real": "Finalizado",
      "fonte": "https://theanalyst.com/articles/senegal-vs-iraq-stats-world-cup-2026 | https://www.reuters.com/sports/soccer/senegal-rout-10-man-iraq-stay-world-cup-hunt-2026-06-26/",
      "placar_original": "Senegal 5 x 0 Iraque"
    },
    {
      "jogo": 63,
      "data": "2026-06-26",
      "diaSemana": "Sexta-feira",
      "horaET": "23:00",
      "horaLocal": "20:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "G",
      "rodadaGrupo": 3.0,
      "equipe1": "Egito",
      "equipe2": "Irã",
      "confronto": "Egito x Irã",
      "estadio": "Lumen Field",
      "cidade": "Seattle",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-26",
      "placar_real": "1-1",
      "vencedor_real": "Empate",
      "gols1_real": 1.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://www.theguardian.com/football/live/2026/jun/27/fifa-world-cup-2026-live-egypt-v-iran-updates-egy-vs-irn-group-g-match-score-latest | https://www.reuters.com/sports/soccer/irans-taremi-criticises-logistical-issues-suggests-side-not-welcome-us-2026-06-27/",
      "placar_original": "Egito 1 x 1 Irã"
    },
    {
      "jogo": 64,
      "data": "2026-06-26",
      "diaSemana": "Sexta-feira",
      "horaET": "23:00",
      "horaLocal": "20:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "G",
      "rodadaGrupo": 3.0,
      "equipe1": "Nova Zelândia",
      "equipe2": "Bélgica",
      "confronto": "Nova Zelândia x Bélgica",
      "estadio": "BC Place",
      "cidade": "Vancouver",
      "pais": "Canadá",
      "status": "Finalizado",
      "data_dt": "2026-06-26",
      "placar_real": "1-5",
      "vencedor_real": "Bélgica",
      "gols1_real": 1.0,
      "gols2_real": 5.0,
      "status_real": "Finalizado",
      "fonte": "https://www.reuters.com/sports/soccer/belgium-beat-new-zealand-5-1-advance-world-cup-knockout-stage-2026-06-27/",
      "placar_original": "Nova Zelândia 1 x 5 Bélgica"
    },
    {
      "jogo": 65,
      "data": "2026-06-26",
      "diaSemana": "Sexta-feira",
      "horaET": "20:00",
      "horaLocal": "19:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "H",
      "rodadaGrupo": 3.0,
      "equipe1": "Cabo Verde",
      "equipe2": "Arábia Saudita",
      "confronto": "Cabo Verde x Arábia Saudita",
      "estadio": "NRG Stadium",
      "cidade": "Houston",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-26",
      "placar_real": "0-0",
      "vencedor_real": "Empate",
      "gols1_real": 0.0,
      "gols2_real": 0.0,
      "status_real": "Finalizado",
      "fonte": "https://www.theguardian.com/football/live/2026/jun/26/cape-verde-v-saudi-arabia-world-cup-2026-live",
      "placar_original": "Cabo Verde 0 x 0 Arábia Saudita"
    },
    {
      "jogo": 66,
      "data": "2026-06-26",
      "diaSemana": "Sexta-feira",
      "horaET": "20:00",
      "horaLocal": "18:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "H",
      "rodadaGrupo": 3.0,
      "equipe1": "Uruguai",
      "equipe2": "Espanha",
      "confronto": "Uruguai x Espanha",
      "estadio": "Estadio Akron",
      "cidade": "Guadalajara",
      "pais": "México",
      "status": "Finalizado",
      "data_dt": "2026-06-26",
      "placar_real": "0-1",
      "vencedor_real": "Espanha",
      "gols1_real": 0.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://english.ahram.org.eg/WorldCup2026/Article/571662 | https://www.theguardian.com/football/live/2026/jun/26/uruguay-v-spain-world-cup-2026-live",
      "placar_original": "Uruguai 0 x 1 Espanha"
    },
    {
      "jogo": 67,
      "data": "2026-06-27",
      "diaSemana": "Sábado",
      "horaET": "17:00",
      "horaLocal": "17:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "L",
      "rodadaGrupo": 3.0,
      "equipe1": "Panamá",
      "equipe2": "Inglaterra",
      "confronto": "Panamá x Inglaterra",
      "estadio": "MetLife Stadium",
      "cidade": "New York/New Jersey",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-27",
      "placar_real": "0-2",
      "vencedor_real": "Inglaterra",
      "gols1_real": 0.0,
      "gols2_real": 2.0,
      "status_real": "Finalizado",
      "fonte": "https://www.reuters.com/sports/soccer/england-beat-panama-2-0-win-group-l-2026-06-27/",
      "placar_original": "Panamá 0 x 2 Inglaterra"
    },
    {
      "jogo": 68,
      "data": "2026-06-27",
      "diaSemana": "Sábado",
      "horaET": "17:00",
      "horaLocal": "17:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "L",
      "rodadaGrupo": 3.0,
      "equipe1": "Croácia",
      "equipe2": "Gana",
      "confronto": "Croácia x Gana",
      "estadio": "Lincoln Financial Field",
      "cidade": "Philadelphia",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-27",
      "placar_real": "2-1",
      "vencedor_real": "Croácia",
      "gols1_real": 2.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://www.reuters.com/sports/soccer/vlasic-header-sends-croatia-into-world-cup-knockouts-with-2-1-win-over-ghana-2026-06-27/",
      "placar_original": "Croácia 2 x 1 Gana"
    },
    {
      "jogo": 69,
      "data": "2026-06-27",
      "diaSemana": "Sábado",
      "horaET": "22:00",
      "horaLocal": "21:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "J",
      "rodadaGrupo": 3.0,
      "equipe1": "Argélia",
      "equipe2": "Áustria",
      "confronto": "Argélia x Áustria",
      "estadio": "Arrowhead Stadium",
      "cidade": "Kansas City",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-27",
      "placar_real": "3-3",
      "vencedor_real": "Empate",
      "gols1_real": 3.0,
      "gols2_real": 3.0,
      "status_real": "Finalizado",
      "fonte": "https://www.reuters.com/sports/soccer/austria-draw-with-algeria-thriller-reach-knockout-stage-iran-out-2026-06-28/",
      "placar_original": "Argélia 3 x 3 Áustria"
    },
    {
      "jogo": 70,
      "data": "2026-06-27",
      "diaSemana": "Sábado",
      "horaET": "22:00",
      "horaLocal": "21:00",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "J",
      "rodadaGrupo": 3.0,
      "equipe1": "Jordânia",
      "equipe2": "Argentina",
      "confronto": "Jordânia x Argentina",
      "estadio": "AT&T Stadium",
      "cidade": "Dallas",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-27",
      "placar_real": "1-3",
      "vencedor_real": "Argentina",
      "gols1_real": 1.0,
      "gols2_real": 3.0,
      "status_real": "Finalizado",
      "fonte": "https://www.reuters.com/sports/soccer/seventh-heaven-messi-argentina-beat-jordan-3-1-2026-06-28/",
      "placar_original": "Jordânia 1 x 3 Argentina"
    },
    {
      "jogo": 71,
      "data": "2026-06-27",
      "diaSemana": "Sábado",
      "horaET": "19:30",
      "horaLocal": "19:30",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "K",
      "rodadaGrupo": 3.0,
      "equipe1": "Colômbia",
      "equipe2": "Portugal",
      "confronto": "Colômbia x Portugal",
      "estadio": "Hard Rock Stadium",
      "cidade": "Miami",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-27",
      "placar_real": "0-0",
      "vencedor_real": "Empate",
      "gols1_real": 0.0,
      "gols2_real": 0.0,
      "status_real": "Finalizado",
      "fonte": "https://www.reuters.com/sports/soccer/colombia-portugal-advance-after-no-bore-draw-miami-2026-06-28/ | https://elpais.com/america-colombia/2026-06-27/colombia-portugal-en-vivo-el-partido-del-grupo-k-del-mundial-2026.html",
      "placar_original": "Colômbia 0 x 0 Portugal"
    },
    {
      "jogo": 72,
      "data": "2026-06-27",
      "diaSemana": "Sábado",
      "horaET": "19:30",
      "horaLocal": "19:30",
      "fase": "Fase de grupos",
      "ordemFase": 1,
      "grupo": "K",
      "rodadaGrupo": 3.0,
      "equipe1": "RD Congo",
      "equipe2": "Uzbequistão",
      "confronto": "RD Congo x Uzbequistão",
      "estadio": "Mercedes-Benz Stadium",
      "cidade": "Atlanta",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-27",
      "placar_real": "3-1",
      "vencedor_real": "RD Congo",
      "gols1_real": 3.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://www.reuters.com/sports/soccer/dr-congo-seal-place-world-cup-knockouts-with-comeback-win-over-uzbekistan-2026-06-28/ | https://www.theguardian.com/football/live/2026/jun/27/dr-congo-v-uzbekistan-world-cup-2026-live",
      "placar_original": "RD Congo 3 x 1 Uzbequistão"
    },
    {
      "jogo": 73,
      "data": "2026-06-28",
      "diaSemana": "Domingo",
      "horaET": "15:00",
      "horaLocal": "12:00",
      "fase": "16 avos de final",
      "ordemFase": 2,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "África do Sul",
      "equipe2": "Canadá",
      "confronto": "África do Sul x Canadá",
      "estadio": "SoFi Stadium",
      "cidade": "Los Angeles",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-28",
      "placar_real": "0-1",
      "vencedor_real": "Canadá",
      "gols1_real": 0.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://www.reuters.com/sports/soccer/canada-score-late-winner-advance-last-16-world-cup-2026-06-28/",
      "placar_original": "África do Sul 0 x 1 Canadá"
    },
    {
      "jogo": 74,
      "data": "2026-06-29",
      "diaSemana": "Segunda-feira",
      "horaET": "16:30",
      "horaLocal": "16:30",
      "fase": "16 avos de final",
      "ordemFase": 2,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Alemanha",
      "equipe2": "Paraguai",
      "confronto": "Alemanha x Paraguai",
      "estadio": "Gillette Stadium",
      "cidade": "Boston",
      "pais": "Estados Unidos",
      "status": "Modelo diário",
      "data_dt": "2026-06-29",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 75,
      "data": "2026-06-29",
      "diaSemana": "Segunda-feira",
      "horaET": "21:00",
      "horaLocal": "19:00",
      "fase": "16 avos de final",
      "ordemFase": 2,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Países Baixos",
      "equipe2": "Marrocos",
      "confronto": "Países Baixos x Marrocos",
      "estadio": "Estadio BBVA",
      "cidade": "Monterrey",
      "pais": "México",
      "status": "Modelo diário",
      "data_dt": "2026-06-29",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 76,
      "data": "2026-06-29",
      "diaSemana": "Segunda-feira",
      "horaET": "13:00",
      "horaLocal": "12:00",
      "fase": "16 avos de final",
      "ordemFase": 2,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Brasil",
      "equipe2": "Japão",
      "confronto": "Brasil x Japão",
      "estadio": "NRG Stadium",
      "cidade": "Houston",
      "pais": "Estados Unidos",
      "status": "Finalizado",
      "data_dt": "2026-06-29",
      "placar_real": "2-1",
      "vencedor_real": "Brasil",
      "gols1_real": 2.0,
      "gols2_real": 1.0,
      "status_real": "Finalizado",
      "fonte": "https://www.reuters.com/sports/soccer/martinelli-rescue-brazil-edge-japan-2-1-last-32-2026-06-29/ | https://www.sofascore.com/news/brazil-2-1-japan-casemiro-leads-late-turnaround | https://www.sofascore.com/football/match/japan-brazil/YUbsvVb",
      "placar_original": "Brasil 2 x 1 Japão"
    },
    {
      "jogo": 77,
      "data": "2026-06-30",
      "diaSemana": "Terça-feira",
      "horaET": "17:00",
      "horaLocal": "17:00",
      "fase": "16 avos de final",
      "ordemFase": 2,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "França",
      "equipe2": "Suécia",
      "confronto": "França x Suécia",
      "estadio": "MetLife Stadium",
      "cidade": "New York/New Jersey",
      "pais": "Estados Unidos",
      "status": "Modelo diário",
      "data_dt": "2026-06-30",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 78,
      "data": "2026-06-30",
      "diaSemana": "Terça-feira",
      "horaET": "13:00",
      "horaLocal": "12:00",
      "fase": "16 avos de final",
      "ordemFase": 2,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Costa do Marfim",
      "equipe2": "Noruega",
      "confronto": "Costa do Marfim x Noruega",
      "estadio": "AT&T Stadium",
      "cidade": "Dallas",
      "pais": "Estados Unidos",
      "status": "Modelo diário",
      "data_dt": "2026-06-30",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 79,
      "data": "2026-06-30",
      "diaSemana": "Terça-feira",
      "horaET": "21:00",
      "horaLocal": "19:00",
      "fase": "16 avos de final",
      "ordemFase": 2,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "México",
      "equipe2": "Equador",
      "confronto": "México x Equador",
      "estadio": "Estadio Azteca",
      "cidade": "Mexico City",
      "pais": "México",
      "status": "Modelo diário",
      "data_dt": "2026-06-30",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 80,
      "data": "2026-07-01",
      "diaSemana": "Quarta-feira",
      "horaET": "12:00",
      "horaLocal": "12:00",
      "fase": "16 avos de final",
      "ordemFase": 2,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Inglaterra",
      "equipe2": "RD Congo",
      "confronto": "Inglaterra x RD Congo",
      "estadio": "Mercedes-Benz Stadium",
      "cidade": "Atlanta",
      "pais": "Estados Unidos",
      "status": "Modelo diário",
      "data_dt": "2026-07-01",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 81,
      "data": "2026-07-01",
      "diaSemana": "Quarta-feira",
      "horaET": "20:00",
      "horaLocal": "17:00",
      "fase": "16 avos de final",
      "ordemFase": 2,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Estados Unidos",
      "equipe2": "Bósnia e Herzegovina",
      "confronto": "Estados Unidos x Bósnia e Herzegovina",
      "estadio": "Levi's Stadium",
      "cidade": "San Francisco Bay Area",
      "pais": "Estados Unidos",
      "status": "Modelo diário",
      "data_dt": "2026-07-01",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 82,
      "data": "2026-07-01",
      "diaSemana": "Quarta-feira",
      "horaET": "16:00",
      "horaLocal": "13:00",
      "fase": "16 avos de final",
      "ordemFase": 2,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Bélgica",
      "equipe2": "Senegal",
      "confronto": "Bélgica x Senegal",
      "estadio": "Lumen Field",
      "cidade": "Seattle",
      "pais": "Estados Unidos",
      "status": "Modelo diário",
      "data_dt": "2026-07-01",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 83,
      "data": "2026-07-02",
      "diaSemana": "Quinta-feira",
      "horaET": "19:00",
      "horaLocal": "19:00",
      "fase": "16 avos de final",
      "ordemFase": 2,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Portugal",
      "equipe2": "Croácia",
      "confronto": "Portugal x Croácia",
      "estadio": "BMO Field",
      "cidade": "Toronto",
      "pais": "Canadá",
      "status": "Modelo diário",
      "data_dt": "2026-07-02",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 84,
      "data": "2026-07-02",
      "diaSemana": "Quinta-feira",
      "horaET": "15:00",
      "horaLocal": "12:00",
      "fase": "16 avos de final",
      "ordemFase": 2,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Espanha",
      "equipe2": "Áustria",
      "confronto": "Espanha x Áustria",
      "estadio": "SoFi Stadium",
      "cidade": "Los Angeles",
      "pais": "Estados Unidos",
      "status": "Modelo diário",
      "data_dt": "2026-07-02",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 85,
      "data": "2026-07-02",
      "diaSemana": "Quinta-feira",
      "horaET": "23:00",
      "horaLocal": "20:00",
      "fase": "16 avos de final",
      "ordemFase": 2,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Suíça",
      "equipe2": "Argélia",
      "confronto": "Suíça x Argélia",
      "estadio": "BC Place",
      "cidade": "Vancouver",
      "pais": "Canadá",
      "status": "Modelo diário",
      "data_dt": "2026-07-02",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 86,
      "data": "2026-07-03",
      "diaSemana": "Sexta-feira",
      "horaET": "18:00",
      "horaLocal": "18:00",
      "fase": "16 avos de final",
      "ordemFase": 2,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Argentina",
      "equipe2": "Cabo Verde",
      "confronto": "Argentina x Cabo Verde",
      "estadio": "Hard Rock Stadium",
      "cidade": "Miami",
      "pais": "Estados Unidos",
      "status": "Modelo diário",
      "data_dt": "2026-07-03",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 87,
      "data": "2026-07-03",
      "diaSemana": "Sexta-feira",
      "horaET": "21:30",
      "horaLocal": "20:30",
      "fase": "16 avos de final",
      "ordemFase": 2,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Colômbia",
      "equipe2": "Gana",
      "confronto": "Colômbia x Gana",
      "estadio": "Arrowhead Stadium",
      "cidade": "Kansas City",
      "pais": "Estados Unidos",
      "status": "Modelo diário",
      "data_dt": "2026-07-03",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 88,
      "data": "2026-07-03",
      "diaSemana": "Sexta-feira",
      "horaET": "14:00",
      "horaLocal": "13:00",
      "fase": "16 avos de final",
      "ordemFase": 2,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Austrália",
      "equipe2": "Egito",
      "confronto": "Austrália x Egito",
      "estadio": "AT&T Stadium",
      "cidade": "Dallas",
      "pais": "Estados Unidos",
      "status": "Modelo diário",
      "data_dt": "2026-07-03",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 89,
      "data": "2026-07-04",
      "diaSemana": "Sábado",
      "horaET": "17:00",
      "horaLocal": "17:00",
      "fase": "Oitavas de final",
      "ordemFase": 3,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Canadá",
      "equipe2": "Países Baixos",
      "confronto": "Canadá x Países Baixos",
      "estadio": "Lincoln Financial Field",
      "cidade": "Philadelphia",
      "pais": "Estados Unidos",
      "status": "Modelo diário",
      "data_dt": "2026-07-04",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 90,
      "data": "2026-07-04",
      "diaSemana": "Sábado",
      "horaET": "13:00",
      "horaLocal": "12:00",
      "fase": "Oitavas de final",
      "ordemFase": 3,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Alemanha",
      "equipe2": "Suécia",
      "confronto": "Alemanha x Suécia",
      "estadio": "NRG Stadium",
      "cidade": "Houston",
      "pais": "Estados Unidos",
      "status": "Modelo diário",
      "data_dt": "2026-07-04",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 91,
      "data": "2026-07-05",
      "diaSemana": "Domingo",
      "horaET": "16:00",
      "horaLocal": "16:00",
      "fase": "Oitavas de final",
      "ordemFase": 3,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Brasil",
      "equipe2": "Costa do Marfim",
      "confronto": "Brasil x Costa do Marfim",
      "estadio": "MetLife Stadium",
      "cidade": "New York/New Jersey",
      "pais": "Estados Unidos",
      "status": "Modelo diário",
      "data_dt": "2026-07-05",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 92,
      "data": "2026-07-05",
      "diaSemana": "Domingo",
      "horaET": "20:00",
      "horaLocal": "18:00",
      "fase": "Oitavas de final",
      "ordemFase": 3,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "México",
      "equipe2": "Inglaterra",
      "confronto": "México x Inglaterra",
      "estadio": "Estadio Azteca",
      "cidade": "Mexico City",
      "pais": "México",
      "status": "Modelo diário",
      "data_dt": "2026-07-05",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 93,
      "data": "2026-07-06",
      "diaSemana": "Segunda-feira",
      "horaET": "15:00",
      "horaLocal": "14:00",
      "fase": "Oitavas de final",
      "ordemFase": 3,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Portugal",
      "equipe2": "Espanha",
      "confronto": "Portugal x Espanha",
      "estadio": "AT&T Stadium",
      "cidade": "Dallas",
      "pais": "Estados Unidos",
      "status": "Modelo diário",
      "data_dt": "2026-07-06",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 94,
      "data": "2026-07-06",
      "diaSemana": "Segunda-feira",
      "horaET": "20:00",
      "horaLocal": "17:00",
      "fase": "Oitavas de final",
      "ordemFase": 3,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Estados Unidos",
      "equipe2": "Bélgica",
      "confronto": "Estados Unidos x Bélgica",
      "estadio": "Lumen Field",
      "cidade": "Seattle",
      "pais": "Estados Unidos",
      "status": "Modelo diário",
      "data_dt": "2026-07-06",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 95,
      "data": "2026-07-07",
      "diaSemana": "Terça-feira",
      "horaET": "12:00",
      "horaLocal": "12:00",
      "fase": "Oitavas de final",
      "ordemFase": 3,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Argentina",
      "equipe2": "Austrália",
      "confronto": "Argentina x Austrália",
      "estadio": "Mercedes-Benz Stadium",
      "cidade": "Atlanta",
      "pais": "Estados Unidos",
      "status": "Modelo diário",
      "data_dt": "2026-07-07",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 96,
      "data": "2026-07-07",
      "diaSemana": "Terça-feira",
      "horaET": "16:00",
      "horaLocal": "13:00",
      "fase": "Oitavas de final",
      "ordemFase": 3,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Suíça",
      "equipe2": "Colômbia",
      "confronto": "Suíça x Colômbia",
      "estadio": "BC Place",
      "cidade": "Vancouver",
      "pais": "Canadá",
      "status": "Modelo diário",
      "data_dt": "2026-07-07",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 97,
      "data": "2026-07-09",
      "diaSemana": "Quinta-feira",
      "horaET": "16:00",
      "horaLocal": "16:00",
      "fase": "Quartas de final",
      "ordemFase": 4,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Canadá",
      "equipe2": "Alemanha",
      "confronto": "Canadá x Alemanha",
      "estadio": "Gillette Stadium",
      "cidade": "Boston",
      "pais": "Estados Unidos",
      "status": "Modelo diário",
      "data_dt": "2026-07-09",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 98,
      "data": "2026-07-10",
      "diaSemana": "Sexta-feira",
      "horaET": "15:00",
      "horaLocal": "12:00",
      "fase": "Quartas de final",
      "ordemFase": 4,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Espanha",
      "equipe2": "Estados Unidos",
      "confronto": "Espanha x Estados Unidos",
      "estadio": "SoFi Stadium",
      "cidade": "Los Angeles",
      "pais": "Estados Unidos",
      "status": "Modelo diário",
      "data_dt": "2026-07-10",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 99,
      "data": "2026-07-11",
      "diaSemana": "Sábado",
      "horaET": "17:00",
      "horaLocal": "17:00",
      "fase": "Quartas de final",
      "ordemFase": 4,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Brasil",
      "equipe2": "Inglaterra",
      "confronto": "Brasil x Inglaterra",
      "estadio": "Hard Rock Stadium",
      "cidade": "Miami",
      "pais": "Estados Unidos",
      "status": "Modelo diário",
      "data_dt": "2026-07-11",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 100,
      "data": "2026-07-11",
      "diaSemana": "Sábado",
      "horaET": "21:00",
      "horaLocal": "20:00",
      "fase": "Quartas de final",
      "ordemFase": 4,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Suíça",
      "equipe2": "Argentina",
      "confronto": "Suíça x Argentina",
      "estadio": "Arrowhead Stadium",
      "cidade": "Kansas City",
      "pais": "Estados Unidos",
      "status": "Modelo diário",
      "data_dt": "2026-07-11",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 101,
      "data": "2026-07-14",
      "diaSemana": "Terça-feira",
      "horaET": "15:00",
      "horaLocal": "14:00",
      "fase": "Semifinais",
      "ordemFase": 5,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Alemanha",
      "equipe2": "Espanha",
      "confronto": "Alemanha x Espanha",
      "estadio": "AT&T Stadium",
      "cidade": "Dallas",
      "pais": "Estados Unidos",
      "status": "Modelo diário",
      "data_dt": "2026-07-14",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 102,
      "data": "2026-07-15",
      "diaSemana": "Quarta-feira",
      "horaET": "15:00",
      "horaLocal": "15:00",
      "fase": "Semifinais",
      "ordemFase": 5,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Brasil",
      "equipe2": "Suíça",
      "confronto": "Brasil x Suíça",
      "estadio": "Mercedes-Benz Stadium",
      "cidade": "Atlanta",
      "pais": "Estados Unidos",
      "status": "Modelo diário",
      "data_dt": "2026-07-15",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 103,
      "data": "2026-07-18",
      "diaSemana": "Sábado",
      "horaET": "17:00",
      "horaLocal": "17:00",
      "fase": "Disputa de 3º lugar",
      "ordemFase": 6,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Espanha",
      "equipe2": "Suíça",
      "confronto": "Espanha x Suíça",
      "estadio": "Hard Rock Stadium",
      "cidade": "Miami",
      "pais": "Estados Unidos",
      "status": "Modelo diário",
      "data_dt": "2026-07-18",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    },
    {
      "jogo": 104,
      "data": "2026-07-19",
      "diaSemana": "Domingo",
      "horaET": "15:00",
      "horaLocal": "15:00",
      "fase": "Final",
      "ordemFase": 7,
      "grupo": null,
      "rodadaGrupo": 0.0,
      "equipe1": "Alemanha",
      "equipe2": "Brasil",
      "confronto": "Alemanha x Brasil",
      "estadio": "MetLife Stadium",
      "cidade": "New York/New Jersey",
      "pais": "Estados Unidos",
      "status": "Modelo diário",
      "data_dt": "2026-07-19",
      "placar_real": null,
      "vencedor_real": null,
      "gols1_real": null,
      "gols2_real": null,
      "status_real": null,
      "fonte": null,
      "placar_original": null
    }
  ]
};
