
name: ETL
on:
  push:
    paths: ['**']
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=." >> $GITHUB_ENV

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install numpy pandas
      - run: python -m worldcup.pipeline
